# Generated by Django 5.2.17 on 2026-09-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('job_seeker', 'Job Seeker'), ('company', 'Company')], default='job_seeker', max_length=20),
        ),
    ]
